### ISSUE TITLE
Missing repository following docker dev instructions

### ISSUE THREAD

**Issue by imartinezortiz** [thm-projects/frag.jetzt#3]
I wanted to test a local installation with docker but seems that the [docker-orchestration project](https://git.thm.de/swtp-2020/docker-orchestration) it is a private, or is it a different one ?.

  Am I right understanding that this project requires an Arsnova installation and this project is built on top of it ?

**Comment by tekay** [comment]
Hi, thanks for raising that issue.
I've made the orchestration repository public.

We are currently working on a standalone backend because yeah, this project is a new frontend that uses the ARSnova backend.
I'd recomment checking it out if you just want to test it locally. We will probably switch to the new backend in the next few weeks.

To do so:
* Use this project (frag.jetzt) with the branch `adapt-to-the-backend` ( be aware: We are still working on that branch and rebasing it quiet regularly to keep up with changes in `master`
* Use this orchestration for all things backend: https://git.thm.de/arsnova/frag.jetzt-docker-orchestration

Compared to the old orchestration it's very lightweight.

**Comment by imartinezortiz** [comment]
Many thanks it works flawlessly, and thanks for publish the `adapt-to-the-backend` branch.

**Comment by tekay** [comment]
Happy to help :)

If you find bugs etc. just let us know. As mentioned, we are still testing the new backend and are happy about feedback.

Closing this issue.
